language: cpp
compiler:
  - gcc
  - clang

before_script:
  - sudo apt-add-repository -y ppa:czchen/travis-ci
  - sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-proper
  - sudo apt-get update -y
  - sudo apt-get install -y cmake
  - sudo apt-get install -y ubuntu-sdk

script: mkdir build && cd build && cmake .. && make
