language: cpp
compiler:
  - gcc
  - clang

before_script:
  - 'echo "deb http://archive.ubuntu.com/ubuntu precise-backports main restricted universe multiverse" > sudo tee -a /etc/apt/sources.list'
  - sudo add-apt-repository -y ppa:canonical-qt5-edgers/qt5-proper
  - sudo apt-get update -y
  - sudo apt-get install -y cmake/precise-backports
  - sudo apt-get install -y ubuntu-sdk

script: mkdir build && cd build && cmake .. && make
